export default [
    {
      path:"/",
      name:"Layout",
      redirect:"/index",
      component:()=>import("../views/LayOut.vue"),
      children:[
        {
          path:"/index",
          name:"index",
          component:()=>import("@/views/index/HomeIndex.vue")
        },
        {
          path:"/orders/list",
          name:"orders_list",
          component:()=>import("@/views/orders/OrdersList"),
          meta:{
            bread:["订单管理","订单列表"]
          }
        },{
          path:"/waybill/in",
          name:"waybill_in",
          component:()=>import("@/views/waybill/WayBillIn"),
          meta:{
            bread:["运单管理","运单录入"]
          }
        },{
          path:"/waybill/list",
          name:"waybill_list",
          component:()=>import("@/views/waybill/WayBillList"),
          meta:{
            bread:["运单管理","运单列表"],
            keepAlive:true
          }
        },{
          path:"/waybill/list/detail",
          name:"waybill_list_detail",
          component:()=>import("@/views/waybill/WaybillDetail"),
          meta:{
            bread:["运单管理","运单列表","运单详情"]
          }
        },{
          path:"/depart/data",
          name:"depart_data",
          component:()=>import("@/views/depart/DepartData"),
          meta:{
            bread:["发车管理","发车数据单"],
            keepAlive:true
          }
        },{
          path:"/depart/data/detail",
          name:"depart_data_detail",
          component:()=>import("@/views/depart/DepartDetail"),
          meta:{
            bread:["发车管理","发车数据单","运单详情"]
          }
        },{
          path:"/carrier/driverlist",
          name:"carrier_driverlist",
          component:()=>import("@/views/carrier/CarrierList"),
          meta:{
            bread:["承运商管理","承运司机列表"]
          }
        },{
          path:"/customer",
          name:"customer",
          component:()=>import("@/views/customer/customerManage"),
          meta:{
            bread:["客户管理"]
          }
        },{
          path:"/finance/info",
          name:"finance_info",
          component:()=>import("@/views/finance/financeInfo"),
          meta:{
            bread:["财务管理","客户对账单"]
          }
        }
      ]
    },
    {
      path:"/login",
      name:"Login",
      component:()=>import("../views/LoginVue.vue")
    }
]